-- ============================================================
-- ROYALE EXPERIENCE GLOBAL CONCEPT (REGC) — Supabase schema
-- Run this in the Supabase SQL Editor.
-- ============================================================

-- ------------------------------------------------------------
-- PRODUCTS
-- ------------------------------------------------------------
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  category text not null default 'staples',
  price numeric(12,2) not null default 0,
  old_price numeric(12,2),
  short_description text,
  description text,
  image text,
  badge text,
  featured boolean not null default false,
  active boolean not null default true,
  stock int not null default 0,
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- ORDERS
-- ------------------------------------------------------------
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_no text not null unique,
  name text not null,
  email text not null,
  phone text not null,
  address text not null,
  subtotal numeric(12,2) not null default 0,
  delivery_fee numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  currency text not null default 'NGN',
  payment_method text not null default 'bank',
  status text not null default 'pending',
  items jsonb not null default '[]'::jsonb,
  payment_ref text,
  payment_status text not null default 'unpaid',
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- SETTINGS (key/value)
-- ------------------------------------------------------------
create table if not exists public.settings (
  key text primary key,
  value text not null default ''
);

-- ------------------------------------------------------------
-- ADMIN USERS (password stored as password_hash)
-- ------------------------------------------------------------
create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- Indexes
-- ------------------------------------------------------------
create index if not exists idx_products_active on public.products(active);
create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_orders_created on public.orders(created_at desc);

-- ============================================================
-- Row Level Security
-- ============================================================
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.settings enable row level security;
alter table public.admins enable row level security;

-- Public can read products and the public settings subset.
drop policy if exists "public read products" on public.products;
create policy "public read products" on public.products
  for select using (active = true);

-- Note: the PHP backend uses the service_role key, which bypasses RLS,
-- so we don't need write policies for it. If you ever switch to the
-- anon key on the client, add appropriate policies.

-- ============================================================
-- Initial settings
-- ============================================================
insert into public.settings (key, value) values
  ('bank_name', 'Zenith Bank'),
  ('account_name', 'Royale Experience Global Concept'),
  ('account_number', '0000000000'),
  ('payment_instructions', 'After placing your order, kindly transfer the total amount to the account below and your order will be processed upon confirmation.'),
  ('delivery_fee', '1000'),
  ('site_whatsapp', '2348166978348'),
  ('site_address', 'Lagos, Nigeria'),
  ('site_tiktok', 'https://www.tiktok.com/@royaleexperienceglobalconcept'),
  ('admin_email', ''),
  ('mail_from', ''),
  ('mail_from_name', 'Royale Experience Global Concept'),
  ('smtp_host', ''),
  ('smtp_port', '587'),
  ('smtp_user', ''),
  ('smtp_pass', ''),
  ('smtp_secure', 'tls'),
  ('telegram_bot_token', ''),
  ('telegram_chat_id', ''),
  ('telegram_api_base', 'https://api.telegram.org'),
  ('notify_customer_order', '1'),
  ('notify_customer_payment', '1'),
  ('notify_customer_status', '1'),
  ('email_include_bank', '0'),
  ('notify_admin_email', '1'),
  ('notify_admin_telegram', '1'),
  ('notify_admin_payment', '1'),
  ('rivo_api_key', ''),
  ('rivo_webhook_secret', ''),
  ('rivo_enabled', '0')
on conflict (key) do nothing;

-- ============================================================
-- Seed products (REGC foodstuff catalog)
-- ============================================================
insert into public.products
  (name, slug, category, price, old_price, short_description, description, image, badge, featured, stock)
values
  -- Staples (Grains & Staples)
  ('Foreign Premium Rice (Congo Plate)', 'foreign-premium-rice', 'staples', 1600, NULL,
   'Premium imported rice, clean and long-grain — a reliable choice for daily family meals.',
   'Premium imported foreign rice, carefully sourced and clean. Ideal for everyday family cooking, jollof, fried rice and plain boiled rice. Sold per Congo plate.',
   '/products/foreign-premium-rice.jpg', 'BEST SELLER', true, 100),
  ('Beans (1kg)', 'beans', 'staples', 1000, NULL,
   'Clean, quality beans — great for porridge, moin-moin and protein-rich family meals.',
   'High-quality cleaned beans, perfect for bean porridge, moin-moin, akara and other nutritious family meals. Sold per kilogram.',
   '/products/beans.jpg', 'NATURAL', true, 100),
  ('Garri (1kg)', 'garri', 'staples', 300, NULL,
   'Fresh, crunchy garri — enjoy as soak-and-eat or soft eba.',
   'Fresh, well-processed garri with a great taste. Perfect for soak-and-eat with groundnut or as soft, smooth eba for any soup. Sold per kilogram.',
   '/products/garri.jpg', 'NATURAL', false, 100),
  ('Yam Flour (1kg)', 'yam-flour', 'staples', 1500, NULL,
   'Smooth yam flour for fluffy, stretchy amala every time.',
   'Premium yam flour that gives you soft, stretchy and fluffy amala every time. Perfect with ewedu, gbegiri and abula. Sold per kilogram.',
   '/products/yam-flour.jpg', 'NATURAL', false, 100),
  ('Pap — Brown, White & Yellow (5kg)', 'pap-5kg', 'staples', 5500, NULL,
   'Ogi/pap in your choice of brown, white or yellow — smooth, wholesome and easy to prepare.',
   'Quality ogi (pap) prepared from fresh grains. Available in brown, white or yellow. Great for breakfast, weaning and convalescents. Sold as 5kg pack.',
   '/products/pap.jpg', 'POPULAR', true, 100),
  ('Pap (Congo Plate)', 'pap-congo-plate', 'staples', 3000, NULL,
   'Freshly prepared smooth ogi — classic Nigerian breakfast staple.',
   'Freshly prepared smooth ogi (pap), a classic Nigerian breakfast staple that pairs perfectly with akara, moi-moi or kuli-kuli. Sold per Congo plate.',
   '/products/pap.jpg', NULL, false, 100),
  ('Pap (1kg)', 'pap-1kg', 'staples', 1500, NULL,
   'Smooth, wholesome ogi for a nourishing start to your day.',
   'Smooth, wholesome ogi made from quality grains. Perfect for a nourishing start to your day. Sold per kilogram.',
   '/products/pap.jpg', NULL, false, 100),
  ('Sugar (1kg)', 'sugar', 'staples', 1500, NULL,
   'Clean, granulated sugar — perfect for beverages, baking and everyday use.',
   'Clean, granulated white sugar, perfect for tea, beverages, baking and everyday use. Sold per kilogram.',
   '/products/sugar.jpg', NULL, false, 100),

  -- Oils (Oils & Fats)
  ('Palm Oil (1 Litre)', 'palm-oil-1l', 'oils', 1600, NULL,
   'Fresh, rich red palm oil with authentic colour and aroma.',
   'Fresh, rich red palm oil with the authentic colour and aroma Nigerian cooking deserves. Perfect for stews, soups and frying. Sold per litre.',
   '/products/palm-oil.jpg', 'BEST SELLER', true, 100),
  ('Palm Oil (5 Litres)', 'palm-oil-5l', 'oils', 8000, NULL,
   'Quality red palm oil in a convenient 5-litre pack for larger households.',
   'Quality red palm oil in a convenient 5-litre pack — ideal for larger households, caterers and bulk cooking.',
   '/products/palm-oil.jpg', NULL, false, 100),
  ('Palm Oil (25kg)', 'palm-oil-25kg', 'oils', 4600, NULL,
   'Bulk red palm oil for serious cooking, caterers and businesses.',
   'Bulk red palm oil for serious cooking, caterers and small businesses. Great value for heavy use. Sold as 25kg.',
   '/products/palm-oil.jpg', NULL, false, 100),
  ('Vegetable Oil (1 Litre)', 'vegetable-oil', 'oils', 2500, NULL,
   'Light, healthy vegetable oil for all your frying and cooking needs.',
   'Light and healthy vegetable oil, perfect for frying, baking and everyday cooking. Sold per litre.',
   '/products/vegetable-oil.jpg', NULL, false, 100),
  ('Groundnut Oil (1 Litre)', 'groundnut-oil', 'oils', 3500, NULL,
   'Pure groundnut oil — rich flavour for frying and sauces.',
   'Pure groundnut oil with a rich, natural flavour. Great for frying, salads and sauces. Sold per litre.',
   '/products/groundnut-oil.jpg', 'PREMIUM', false, 100),

  -- Produce (Fresh Produce)
  ('Fresh Tatashe Pepper (1kg)', 'tatashe-pepper', 'produce', 710, NULL,
   'Large, fleshy red bell peppers — perfect for stews and pepper sauces.',
   'Fresh, fleshy tatashe (red bell pepper) — the key ingredient for rich Nigerian stews and pepper sauces. Sold per kilogram.',
   '/products/tatashe-pepper.jpg', 'FRESH', false, 100),
  ('Fresh Rodo Pepper (1kg)', 'rodo-pepper', 'produce', 951, NULL,
   'Spicy fresh rodo (scotch bonnet) peppers for that authentic heat.',
   'Fresh, spicy rodo (scotch bonnet) peppers for the authentic heat in your soups, stews and pepper sauce. Sold per kilogram.',
   '/products/rodo-pepper.jpg', 'FRESH', false, 100),
  ('Fresh Tomato (1kg)', 'fresh-tomato', 'produce', 1000, NULL,
   'Ripe, juicy tomatoes — the base of every great Nigerian stew.',
   'Ripe, juicy fresh tomatoes — the base of every great Nigerian stew and pepper sauce. Sold per kilogram.',
   '/products/fresh-tomato.jpg', 'FRESH', true, 100),
  ('Fresh Onion (1kg)', 'fresh-onion', 'produce', 1000, NULL,
   'Pungent, fresh onions for seasoning every meal.',
   'Fresh, pungent onions for seasoning and flavouring every meal. Sold per kilogram.',
   '/products/fresh-onion.jpg', 'FRESH', false, 100),
  ('Fresh Ginger (1kg)', 'fresh-ginger', 'produce', 350, NULL,
   'Aromatic fresh ginger — for tea, cooking and wellness.',
   'Aromatic fresh ginger, perfect for ginger tea, cooking, sauces and natural wellness remedies. Sold per kilogram.',
   '/products/fresh-ginger.jpg', NULL, false, 100),

  -- Frozen (Frozen Foods)
  ('Frozen Fish (1kg)', 'frozen-fish', 'frozen', 1500, NULL,
   'Clean, well-frozen fish — fresh taste for soups and stews.',
   'Clean, well-frozen fish, great for Nigerian fish stews, pepper soup and frying. Sold per kilogram.',
   '/products/frozen-fish.jpg', NULL, true, 100),
  ('Frozen Chicken (1kg)', 'frozen-chicken', 'frozen', 2000, NULL,
   'Quality frozen chicken — tender and ready for any recipe.',
   'Quality frozen chicken, tender and versatile for frying, stewing or roasting. Sold per kilogram.',
   '/products/frozen-chicken.jpg', 'POPULAR', false, 100),
  ('Frozen Turkey (1kg)', 'frozen-turkey', 'frozen', 3500, NULL,
   'Large, meaty frozen turkey — the centrepiece of festive meals.',
   'Large, meaty frozen turkey — the centrepiece of festive celebrations and family meals. Sold per kilogram.',
   '/products/frozen-turkey.jpg', NULL, false, 100),

  -- Pantry (Pantry & Spices)
  ('Spices (Jar)', 'spices-jar', 'pantry', 300, NULL,
   'Assorted quality spices in a convenient jar for everyday seasoning.',
   'Assorted quality spices in a convenient jar — elevate the flavour of your everyday meals. Sold per jar.',
   '/products/spices-jar.jpg', NULL, false, 100),
  ('Seasoning (1kg)', 'seasoning', 'pantry', 1000, NULL,
   'Rich seasoning cubes and powder for deep, savoury flavour.',
   'Rich seasoning for deep, savoury flavour in soups, stews and rice dishes. Sold per kilogram.',
   '/products/seasoning.jpg', NULL, false, 100),
  ('Dried Hibiscus (1kg)', 'dried-hibiscus', 'pantry', 710, NULL,
   'Clean dried hibiscus leaves — brew the perfect zobo or herbal tea.',
   'Clean, dried hibiscus (zobo) leaves for brewing refreshing zobo drink or herbal tea at home. Sold per kilogram.',
   '/products/dried-hibiscus.jpg', NULL, false, 100),

  -- Beverages (Beverages & Refreshments)
  ('Premium Dates (1kg)', 'premium-dates', 'beverages', 2500, NULL,
   'Sweet, premium dates — a natural snack and Ramadan favourite.',
   'Sweet, premium dates — a natural energy snack, a Ramadan favourite, and great for baking and smoothies. Sold per kilogram.',
   '/products/premium-dates.jpg', 'RAMADAN', true, 100),
  ('Luxury Dates (1kg)', 'luxury-dates', 'beverages', 3500, NULL,
   'Selected luxury dates — soft, rich and perfect for gifting.',
   'Selected luxury dates, soft and rich in natural sweetness. Perfect for gifting and special occasions. Sold per kilogram.',
   '/products/premium-dates.jpg', 'LUXURY', false, 100),
  ('Tigernuts (500g)', 'tigernuts', 'beverages', 500, NULL,
   'Crunchy, healthy tigernuts — a satisfying natural snack.',
   'Crunchy, healthy tigernuts, naturally sweet and full of fibre. A satisfying and nutritious snack. Sold per 500g pack.',
   '/products/tigernuts.jpg', NULL, false, 100),
  ('Zobo Drink (500g)', 'zobo-drink', 'beverages', 350, NULL,
   'Make chilled zobo at home with our quality zobo mix.',
   'Everything you need to brew chilled, refreshing zobo at home. Sold per 500g pack.',
   '/products/zobo-drink.jpg', NULL, false, 100),

  -- Hampers (Gift Hampers)
  ('Gift Food Hamper (Pack)', 'gift-food-hamper', 'hampers', 15000, NULL,
   'A curated box of quality foodstuff — the perfect gift for every occasion.',
   'A curated gift box filled with quality foodstuff selections — perfect for weddings, housewarming, Ramadan and corporate gifting. Customise your hamper by contacting us.',
   '/products/gift-food-hamper.jpg', 'GIFT', true, 100)

on conflict (slug) do nothing;